import express from 'express'; import cookieParser from 'cookie-parser'; import helmet from 'helmet'; import { randomBytes, scryptSync, timingSafeEqual, createHash, randomUUID } from 'node:crypto'; import type Database from 'better-sqlite3'; import { commandSchema, credentialsSchema, type Task, type Message } from '../shared/contracts.js';
const hashToken=(v:string)=>createHash('sha256').update(v).digest('hex');
const hashPassword=(p:string,s=randomBytes(16).toString('hex'))=>`${s}:${scryptSync(p,s,64).toString('hex')}`;
const verifyPassword=(p:string,h:string)=>{const [s,key]=h.split(':'); if(!s||!key)return false; return timingSafeEqual(Buffer.from(key,'hex'),scryptSync(p,s,64));};
function taskFrom(row:any):Task{return {id:row.id,title:row.title,status:'open',createdAt:row.created_at,mode:'live'};}
export function provisionProductionOwner(db:Database.Database){
 if(process.env.NODE_ENV!=='production')return;
 const parsed=credentialsSchema.safeParse({username:process.env.JARVIS_OWNER_USERNAME,password:process.env.JARVIS_OWNER_PASSWORD});
 if(!parsed.success)throw new Error('Production requires JARVIS_OWNER_USERNAME and a 10–128 character JARVIS_OWNER_PASSWORD');
 const username=parsed.data.username.toLowerCase();
 const accounts=db.prepare('SELECT id,username FROM accounts').all() as {id:number,username:string}[];
 if(accounts.length===0){db.prepare('INSERT INTO accounts(username,password_hash,created_at) VALUES(?,?,?)').run(username,hashPassword(parsed.data.password),new Date().toISOString());return;}
 if(accounts.length!==1||accounts[0]?.username!==username)throw new Error('Production database must contain only the configured owner account');
}
export function createApp(db:Database.Database){const app=express(); app.disable('x-powered-by'); app.use(helmet({contentSecurityPolicy:false})); app.use(express.json({limit:'32kb'})); app.use(cookieParser());
 app.get('/api/health',(_req,res)=>{db.prepare('SELECT 1').get();res.json({status:'ok'});});
 const auth=(req:express.Request,res:express.Response,next:express.NextFunction)=>{const token=req.cookies['jarvis_session']; if(!token)return res.status(401).json({error:'Authentication required'}); const row=db.prepare("SELECT account_id FROM sessions WHERE token_hash=? AND expires_at>?").get(hashToken(token),new Date().toISOString()) as {account_id:number}|undefined; if(!row)return res.status(401).json({error:'Session expired'}); res.locals.accountId=row.account_id; next();};
 app.post('/api/auth/register',(req,res)=>{if(process.env.NODE_ENV==='production')return res.status(404).json({error:'Not found'});const parsed=credentialsSchema.safeParse(req.body); if(!parsed.success)return res.status(400).json({error:'Username or password is invalid'}); try{const info=db.prepare('INSERT INTO accounts(username,password_hash,created_at) VALUES(?,?,?)').run(parsed.data.username.toLowerCase(),hashPassword(parsed.data.password),new Date().toISOString()); issueSession(Number(info.lastInsertRowid),res); res.status(201).json({username:parsed.data.username.toLowerCase()});}catch{return res.status(409).json({error:'Account already exists'});}});
 app.post('/api/auth/login',(req,res)=>{const parsed=credentialsSchema.safeParse(req.body); if(!parsed.success)return res.status(400).json({error:'Username or password is invalid'}); const row=db.prepare('SELECT id,password_hash FROM accounts WHERE username=?').get(parsed.data.username.toLowerCase()) as {id:number,password_hash:string}|undefined; if(!row||!verifyPassword(parsed.data.password,row.password_hash))return res.status(401).json({error:'Invalid credentials'}); issueSession(row.id,res); res.json({username:parsed.data.username.toLowerCase()});});
 function issueSession(accountId:number,res:express.Response){const token=randomBytes(32).toString('base64url'); const expires=new Date(Date.now()+7*86400000); db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(hashToken(token),accountId,expires.toISOString()); res.cookie('jarvis_session',token,{httpOnly:true,sameSite:'strict',secure:process.env.NODE_ENV==='production',expires,path:'/'});}
 app.post('/api/auth/logout',auth,(req,res)=>{const token=req.cookies['jarvis_session']; db.prepare('DELETE FROM sessions WHERE token_hash=?').run(hashToken(token)); res.clearCookie('jarvis_session',{path:'/'}); res.status(204).end();});
 app.get('/api/tasks',auth,(_req,res)=>{const rows=db.prepare('SELECT * FROM tasks WHERE account_id=? ORDER BY id DESC').all(res.locals.accountId);res.json({tasks:rows.map(taskFrom)});});
 app.get('/api/messages',auth,(_req,res)=>{const rows=db.prepare('SELECT id,role,body,mode,created_at FROM messages WHERE account_id=? ORDER BY created_at,id').all(res.locals.accountId) as any[];res.json({messages:rows.map(r=>({id:r.id,role:r.role,text:r.body,mode:r.mode,createdAt:r.created_at}))});});
 app.post('/api/commands',auth,(req,res)=>{const parsed=commandSchema.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'Enter a command of 1–300 characters and a valid mode'}); const title=parseTask(parsed.data.text);if(!title)return res.status(422).json({error:'Try “Add a task to review JARVIS” or “Lägg till en uppgift att granska JARVIS”.'}); const now=new Date().toISOString();if(parsed.data.mode==='demo'){const task:Task={id:0,title,status:'open',createdAt:now,mode:'demo'};return res.json({task,persisted:false,messages:conversation(parsed.data.text,task,now)});} const save=db.transaction(()=>{const info=db.prepare('INSERT INTO tasks(account_id,title,created_at) VALUES(?,?,?)').run(res.locals.accountId,title,now);const task:Task={id:Number(info.lastInsertRowid),title,status:'open',createdAt:now,mode:'live'};for(const m of conversation(parsed.data.text,task,now))db.prepare('INSERT INTO messages VALUES(?,?,?,?,?,?)').run(m.id,res.locals.accountId,m.role,m.text,'live',m.createdAt);return task;});const task=save();res.status(201).json({task,persisted:true,messages:conversationRows(db,res.locals.accountId).slice(-2)});});
 return app;}
function parseTask(text:string){const patterns=[/^add (?:a )?task(?: to)?\s+(.+)$/i,/^lägg till (?:en )?uppgift(?: att)?\s+(.+)$/i];for(const p of patterns){const m=text.trim().match(p);if(m?.[1])return m[1].trim().slice(0,200);}return null;}
function conversation(input:string,task:Task,at:string):Message[]{return[{id:randomUUID(),role:'user',text:input,createdAt:at,mode:task.mode},{id:randomUUID(),role:'assistant',text:`Task added: ${task.title}${task.mode==='demo'?' (Demo only — not saved)':''}`,createdAt:at,mode:task.mode}];}
function conversationRows(db:Database.Database,accountId:number):Message[]{return (db.prepare('SELECT id,role,body,mode,created_at FROM messages WHERE account_id=? ORDER BY created_at,id').all(accountId) as any[]).map(r=>({id:r.id,role:r.role,text:r.body,mode:r.mode,createdAt:r.created_at}));}
