import React,{useEffect,useState} from 'react';import{createRoot}from'react-dom/client';import type{Message,Mode,Task}from'../../shared/contracts';import'./styles.css';
async function api(path:string,options?:RequestInit){const r=await fetch(`/api${path}`,{...options,headers:{'content-type':'application/json',...(options?.headers||{})}});if(!r.ok){const b=await r.json().catch(()=>({}));throw new Error(b.error||`Request failed (${r.status})`);}return r.status===204?null:r.json();}
const nav=['Overview','Conversation','Screen','Workflows','Workspace','Briefings','Tasks','Memory','Integrations','Settings'];
function App(){const[auth,setAuth]=useState(false),[form,setForm]=useState({username:'',password:''}),[error,setError]=useState(''),[tasks,setTasks]=useState<Task[]>([]),[messages,setMessages]=useState<Message[]>([]),[text,setText]=useState('Add a task to review JARVIS'),[mode,setMode]=useState<Mode>('live'),[busy,setBusy]=useState(false);
 const load=async()=>{try{const[t,m]=await Promise.all([api('/tasks'),api('/messages')]);setTasks(t.tasks);setMessages(m.messages);setAuth(true)}catch{setAuth(false)}};useEffect(()=>{void load()},[]);
 const authenticate=async(kind:'login'|'register')=>{setError('');try{await api(`/auth/${kind}`,{method:'POST',body:JSON.stringify(form)});await load()}catch(e){setError((e as Error).message)}};
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const result=await api('/commands',{method:'POST',body:JSON.stringify({text,mode})});if(result.persisted)await load();else{setMessages(v=>[...v,...result.messages]);setTasks(v=>[result.task,...v])}setText('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 if(!auth)return <main className="login"><section className="login-card"><span className="eyebrow">SECURE ACCESS</span><h1>JARVIS</h1><p>Your local command center. Create an account or sign in to continue.</p><label>Username<input autoComplete="username" value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/></label><label>Password<input type="password" autoComplete="current-password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label>{error&&<p className="error" role="alert">{error}</p>}<div className="auth-actions"><button onClick={()=>authenticate('login')}>Sign in</button><button className="secondary" onClick={()=>authenticate('register')}>Create account</button></div><small>Passwords require 10 characters. Credentials remain server-side.</small></section></main>;
 return <div className="shell"><aside><div className="brand"><i/>JARVIS</div><nav aria-label="Primary">{nav.map((n,i)=><button key={n} className={i===0?'active':''} disabled={i>1}><span>{String(i+1).padStart(2,'0')}</span>{n}{i>1&&<em>Later</em>}</button>)}</nav><button className="logout" onClick={async()=>{await api('/auth/logout',{method:'POST'});setAuth(false)}}>Sign out</button></aside><main className="canvas"><header><div><span className="eyebrow">COMMAND CENTER / PHASE A</span><h1>Good evening.</h1><p>What would you like to accomplish?</p></div><span className="status"><i/> Local systems ready</span></header><section className="core" aria-label="Assistant state: idle"><div className="orbit o1"/><div className="orbit o2"/><div className="core-label"><strong>J</strong><span>IDLE</span></div></section><section className="conversation" aria-live="polite">{messages.length===0?<div className="empty"><h2>Ready for your first task</h2><p>Type “Add a task to review JARVIS”. Swedish is supported too.</p></div>:messages.map(m=><article key={m.id} className={m.role}><span>{m.role==='assistant'?'JARVIS':'YOU'} · {m.mode.toUpperCase()}</span><p>{m.text}</p></article>)}</section><form className="composer" onSubmit={submit}><label className="sr-only" htmlFor="command">Command</label><input id="command" value={text} onChange={e=>setText(e.target.value)} placeholder="Type a command…" disabled={busy}/><select aria-label="Execution mode" value={mode} onChange={e=>setMode(e.target.value as Mode)}><option value="live">Live · saves</option><option value="demo">Demo · no writes</option></select><button disabled={busy||!text.trim()}>{busy?'Saving…':'Send'}</button></form>{error&&<p className="error banner" role="alert">{error}</p>}</main><aside className="context"><span className="eyebrow">CURRENT CONTEXT</span><section><h2>Tasks</h2><strong>{tasks.filter(t=>t.mode==='live').length}</strong><small>persisted for this account</small></section><section><h2>Capabilities</h2><ul><li><i className="good"/>Tasks <b>Working</b></li><li><i/>AI providers <b>Needs configuration</b></li><li><i/>Native actions <b>Requires companion</b></li></ul></section><p className="notice">Demo items are temporary and disappear on refresh. Live items persist in SQLite when the host storage persists.</p></aside></div>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
